#!/usr/bin/env python3
"""
Generates support/classicui/chome_icons32.h - one 32x32 flat silhouette per system.

Kept as a generator rather than hand-typed art because the shapes are built from
rectangles and circles, and a table of 32x32 character rows is unreviewable by eye:
a stray column in row 19 of a hand-typed icon is invisible in a diff and obvious on
a TV. Re-run it after editing a shape:

    python3 support/classicui/tools/gen_icons32.py

Single ink colour, no shading, per the brief. The renderer scales the grid to
whatever box the card gives it, so these are drawn at a comfortable size and
sampled down at 240p rather than drawn twice.
"""
import os

N = 32
OUT = os.path.join(os.path.dirname(__file__), "..", "chome_icons32.h")


class G:
    def __init__(self):
        self.g = [[0] * N for _ in range(N)]

    def rect(self, x0, y0, x1, y1, v=1):
        for y in range(max(0, y0), min(N, y1 + 1)):
            for x in range(max(0, x0), min(N, x1 + 1)):
                self.g[y][x] = v

    def frame(self, x0, y0, x1, y1, t=1, v=1):
        self.rect(x0, y0, x1, y0 + t - 1, v)
        self.rect(x0, y1 - t + 1, x1, y1, v)
        self.rect(x0, y0, x0 + t - 1, y1, v)
        self.rect(x1 - t + 1, y0, x1, y1, v)

    def disc(self, cx, cy, r, v=1):
        for y in range(N):
            for x in range(N):
                if (x - cx) ** 2 + (y - cy) ** 2 <= r * r:
                    self.g[y][x] = v

    def rows(self):
        return ["".join("#" if c else "." for c in row) for row in self.g]


def console(slot="top", ports=2, wide=True):
    """A low box: the shared shape of a cartridge console, with a slot and ports."""
    g = G()
    y0, y1 = 11, 23
    x0, x1 = (2, 29) if wide else (5, 26)
    g.rect(x0, y0, x1, y1)
    if slot == "top":                      # cartridge slot on the lid
        g.rect(x0 + 6, y0 - 3, x1 - 6, y0 - 1)
        g.rect(x0 + 8, y0 - 5, x1 - 8, y0 - 4)
    elif slot == "flap":                   # front loader
        g.rect(x0 + 4, y0 + 2, x1 - 4, y0 + 6, 0)
        g.frame(x0 + 4, y0 + 2, x1 - 4, y0 + 6, 1)
    elif slot == "disc":                   # lid circle
        g.disc(16, 17, 6, 0)
        for y in range(N):                 # ring
            for x in range(N):
                d = (x - 16) ** 2 + (y - 17) ** 2
                if 25 <= d <= 36:
                    g.g[y][x] = 1
    step = (x1 - x0 - 4) // max(1, ports)
    for p in range(ports):                 # controller ports along the front
        px = x0 + 3 + p * step
        g.rect(px, y1 - 3, px + 2, y1 - 1, 0)
    return g


def handheld(tall=True):
    g = G()
    if tall:
        g.rect(9, 3, 23, 29)
        g.rect(11, 6, 21, 15, 0)           # screen
        g.frame(11, 6, 21, 15, 1)
        # d-pad and buttons, kept a clear pixel inside the shell so the outline
        # never gets bitten into
        g.rect(13, 20, 15, 26, 0)
        g.rect(12, 22, 17, 24, 0)
        g.disc(20, 24, 1, 0)
        g.disc(20, 20, 1, 0)
    else:
        g.rect(2, 9, 29, 23)
        g.rect(10, 12, 21, 20, 0)
        g.frame(10, 12, 21, 20, 1)
        g.rect(6, 13, 8, 19, 0)
        g.rect(5, 15, 10, 17, 0)
        g.disc(24, 15, 1, 0)
        g.disc(27, 17, 1, 0)
    return g


def cabinet():
    g = G()
    g.rect(6, 2, 25, 29)
    g.rect(8, 4, 23, 8, 0)                 # marquee
    g.rect(8, 10, 23, 18, 0)               # screen
    g.frame(8, 10, 23, 18, 1)
    g.rect(9, 21, 22, 23, 0)               # control panel
    g.rect(4, 27, 27, 29)                  # base
    return g


def computer():
    g = G()
    g.rect(2, 14, 29, 22)                  # wedge keyboard
    g.rect(4, 10, 27, 13)
    for x in range(5, 27, 3):              # keys
        g.rect(x, 16, x + 1, 17, 0)
    g.rect(6, 19, 25, 20, 0)               # space bar
    return g


def n64():
    g = G()
    for i, y in enumerate(range(10, 24)):  # trapezoid
        inset = max(0, (13 - i) // 3)
        g.rect(3 + inset, y, 28 - inset, y)
    g.rect(12, 6, 19, 9)                   # cart
    for p in range(4):
        px = 5 + p * 6
        g.rect(px, 21, px + 2, 23, 0)
    return g


SYSTEMS = [
    ("nes",    console("flap", 2)),
    ("snes",   console("top", 2, wide=False)),
    ("md",     console("top", 2)),
    ("sms",    console("top", 2, wide=False)),
    ("tg16",   console("top", 1, wide=False)),
    ("n64",    n64()),
    ("psx",    console("disc", 2)),
    ("gb",     handheld(True)),
    ("gba",    handheld(False)),
    ("lynx",   handheld(False)),
    ("ws",     handheld(True)),
    ("ngp",    handheld(True)),
    ("a7800",  console("top", 2)),
    ("neogeo", cabinet()),
    ("arcade", cabinet()),
    ("amiga",  computer()),
    ("st",     computer()),
    ("c64",    computer()),
    ("spec",   computer()),
    ("cpc",    computer()),
    ("msx",    computer()),
    ("ao486",  computer()),
    ("apple2", computer()),
]

with open(OUT, "w") as f:
    f.write("""/*
  Per-system icons: 32x32, one flat ink colour, no shading.

  GENERATED by support/classicui/tools/gen_icons32.py - edit the shapes there and
  re-run rather than touching this file, and see that script for why it is generated.

  A system without an entry here falls back to the generic 8x8 set.
*/

#ifndef CHOME_ICONS32_H
#define CHOME_ICONS32_H

#define ICON32 32

struct sysicon_def { const char *id; const char *rows[ICON32]; };

static const sysicon_def sysicons[] =
{
""")
    for name, g in SYSTEMS:
        f.write('\t{ "%s", {\n' % name)
        for r in g.rows():
            f.write('\t\t"%s",\n' % r)
        f.write("\t} },\n")
    f.write("""};

#endif
""")

print("wrote %s with %d icons" % (os.path.normpath(OUT), len(SYSTEMS)))
