#!/bin/sh
#
# Turns a local ScreenScraper credentials file into a header the build includes.
#
#   ss_creds.sh <env-file> <out-header>
#
# ScreenScraper's API sends devid and devpassword on *every* request - they identify
# the application, not the player, and a request without them is refused - so they
# have to be compiled in. The player's own account is a separate pair (ssid and
# sspassword) which comes from MiSTer.ini at runtime and is what earns that player
# their own quota; see the guest-versus-member thread pools on screenscraper.fr.
#
# Compiled in, but not on the compile *command line*: a -D would put the password
# into every build log, into `ps` output while the compiler runs, and into the
# terminal of anyone building with V=1. The header goes under bin/, which the
# repository already ignores wholesale and `make clean` already deletes, so there is
# no new rule to remember and no path that a stray `git add -A` can pick up.
#
# Absent or incomplete credentials are the normal case, not an error: the header is
# removed and chome_ss.cpp compiles with its gate closed, exactly as a shipped build
# does. Nothing is printed either way, because the point is to not say the secret out
# loud.

env="$1"
out="$2"

[ -n "$out" ] || exit 0

if [ ! -f "$env" ]; then rm -f "$out"; exit 0; fi

# The value is everything after the first '=', taken from the first matching line, so
# a password containing '=' survives intact.
#
# Surrounding quotes are stripped, because SS_DEVID="..." is what anyone writing a file
# full of secrets writes, and taking them literally is silent and awful: the quotes get
# escaped into the generated header, the binary sends "abc" instead of abc, and the API
# rejects a credential that looks perfectly correct in every file you inspect. Only a
# matched pair is removed, so a password that genuinely contains a quote is untouched.
field() {
	v=$(sed -n "s/^$1=//p" "$env" | head -1)
	case "$v" in
	'"'*'"') v=$(printf '%s' "$v" | sed -e 's/^"//' -e 's/"$//') ;;
	"'"*"'") v=$(printf '%s' "$v" | sed -e "s/^'//" -e "s/'\$//") ;;
	esac
	printf '%s' "$v"
}

# What the C string literal needs escaped. Backslash first, or it doubles the escapes
# this adds afterwards.
cstr() {
	printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

devid=$(field SS_DEVID)
devpass=$(field SS_DEVPASS)
softname=$(field SS_SOFTNAME)

if [ -z "$devid" ] || [ -z "$devpass" ]; then rm -f "$out"; exit 0; fi

umask 077
tmp="$out.new"
{
	echo "/* Generated by support/classicui/tools/ss_creds.sh. Do not commit or edit. */"
	echo "#define CLASSICUI_SS_DEVID   \"$(cstr "$devid")\""
	echo "#define CLASSICUI_SS_DEVPASS \"$(cstr "$devpass")\""
	[ -n "$softname" ] && echo "#define CLASSICUI_SS_SOFTNAME \"$(cstr "$softname")\""
} > "$tmp"

# Replaced only when the contents actually differ, so the mtime does not move on a
# run that changed nothing.
#
# This is not tidiness, it is the difference between a build and an infinite loop. The
# makefile -include's the generated .d files, so make re-executes itself after building
# them; this script runs at parse time and therefore again on every re-execution. Once
# chome_ss.cpp.d lists this header as a prerequisite, rewriting it each time made that
# .d stale the moment it was written, so make regenerated it, restarted, and went round
# for ever - 119 dependency files and not one object, which is what it looked like from
# outside. Same lesson as the disc state file: compare by content, not by timestamp.
if [ -f "$out" ] && cmp -s "$tmp" "$out"; then rm -f "$tmp"; else mv -f "$tmp" "$out"; fi

exit 0
