/*
  Pictograms: 16x16, one bit per pixel, drawn in a single flat colour.

  GENERATED by support/classicui/tools/icons32.py - do not edit.

  Same sources and the same CC BY 4.0 licence as the system icons; see the header of
  chome_icons32.h and support/classicui/ICONS.md.
*/

#ifndef CHOME_ICONS16_H
#define CHOME_ICONS16_H

#define ICON16 16

struct picto_def { const char *name; const char *rows[ICON16]; };

static const picto_def pictos[] =
{
	// add-favorite  (retroarch, sha256 ecd8b14f3a217ee5)
	{ "star", {
		"................",
		"................",
		".......##.......",
		".......##.......",
		"......####......",
		"......####......",
		"..#############.",
		"...##########...",
		"....########....",
		".....######.....",
		"....########....",
		"....########....",
		"....##....##....",
		"....#......#....",
		"................",
		"................",
	} },
};

#endif
