/*
  Classic Home - video looks.

  A short curated list of presets instead of MiSTer's filter/mask/gamma knobs.
  Each look drives two machines: the scaler, through a real MiSTer preset file
  applied with video_loadPreset() (which persists per core), and the running
  core's own display options, matched by NAME against its CONF_STR and never
  saved into its config - see the preset table in chome_video.cpp for why the
  colour work moved core-side for GB and GBA, and what stays with the scaler
  (the pixel grid, drawn by a polyphase filter so it lands on core pixel
  boundaries at any scale - the one thing a shadow mask cannot promise).

  The filter coefficients, shadow masks, gamma LUTs and .gbp palettes the
  presets reference are generated by vp_install() rather than assumed to be on
  the SD card, so the looks work on a stock install without the community
  filter packs. Files we generated are regenerated when their content changes;
  files without our marker belong to the user and are never touched.

  Every class offers one entry that turns all processing off (Sharp for the CRT
  classes, None for handhelds - None also resets the core-side effects).

  Previews are illustrations rendered in software from the same parameters, not
  captures of a running core.
*/

#ifndef CHOME_VIDEO_H
#define CHOME_VIDEO_H

#include <inttypes.h>

// Video class of a system: picks the default look.
#define VC_CONSOLE  0   // RGB-modded console on a PVM
#define VC_ARCADE   1
#define VC_COMPUTER 2   // 15 kHz home computer, i.e. plugged into a TV
#define VC_VGA      3   // 31 kHz computer monitor, no scanlines
#define VC_GB       4
#define VC_GBC      5
#define VC_GBA      6
#define VC_GG       7   // Sega Game Gear
#define VC_LYNX     8   // Atari Lynx
#define VC_WS       9   // WonderSwan, monochrome
#define VC_WSC     10   // WonderSwan Color
#define VC_NGPC    11   // Neo Geo Pocket Color
#define VC_COUNT   12

// 1 for the handheld classes: they get LCD looks and a shell, never a CRT.
int  vp_class_is_handheld(int vclass);

const char *vp_class_name(int vclass);

// Human-readable, for the "for <hardware>" heading over the shortened list.
const char *vp_class_label(int vclass);
int  vp_class_from_name(const char *s);

// Writes the filters, masks, gamma curves and preset files. Safe to call often:
// only missing files are created.
void vp_install();

int  vp_count();
const char *vp_name(int i);
const char *vp_blurb(int i);

/*
  Looks are offered per video class, not as one global list: a Game Boy game has
  no business being shown a PVM look, and a Mega Drive game has no business being
  shown an LCD one. vp_options_for() returns how many looks apply to a class and
  writes the preset indices into out[], most authentic first - so entry 0 is also
  the default.
*/
#define VP_MAX_OPTIONS 8
int  vp_options_for(int vclass, int *out);

// 1 when every file the preset needs exists.
int  vp_available(int i);

int  vp_default_for(int vclass);

/*
  Effective look for a system in a given class: the user's stored choice when it
  is still valid for that class, else the class default. The choice is keyed by
  system AND class, so a GBC cartridge and a DMG cartridge running in the same
  Game Boy core remember different screens.
*/
int  vp_effective(int sysidx, int vclass);
void vp_set(int sysidx, int vclass, int preset);

// Records the look to apply once the next core has booted, and applies it there.
// vclass_hint < 0 uses the system's own class.
void vp_arm_for_launch(int sysidx, int vclass_hint);
void vp_apply_pending();

/*
  Repeat the core-side half of the session's look, once the ROM is really in.
  chome_core_boot() runs before an MGL's delayed file load, and the core resets
  around that load - see the note at vp_apply_core_side(). No-op when no look
  was applied this session.
*/
void vp_reapply_core_side();

// Applies the look the running core should have, right now rather than at next launch.
int vp_apply_now(int sysidx, int vclass_hint);

// Absolute path of a look's generated preset file, for applying it directly.
int  vp_preset_path(int i, char *out, int len);

/*
  Absolute path of a look's static preview image (classicui/lookshots/<id>.png),
  1 only when the file exists. A distribution-provided zoomed shot of the real
  effect - phosphors, grid - which the Display screen prefers over the computed
  illustration, because the real filters live in the scaler and cannot be read
  back.
*/
int  vp_lookshot_path(int i, char *out, int len);

/*
  Preview of a look, cached. When ref is non-null it is used as the source frame -
  a real capture of the user's own game - and the look is applied over it; with no
  reference a synthetic test pattern stands in.

  Either way the filter itself is a software approximation: the real filters live
  downstream in the FPGA scaler and nothing can read back from there (the capture
  buffer at MISTER_SCALER_BASEADDR holds the core's frame *before* scaling). So the
  content is real, the effect is simulated.
*/
const uint32_t *vp_preview(int i, int w, int h, const uint32_t *ref);

/* --------------------------------------------------- the analog output ----- */

/*
  What the analog output is doing to this front-end, as facts rather than as settings.

  Two users have now reported the same class of fault: a rolling picture on a CRT over
  component, and "scrambled b/w mess with rolling image on my crt with svideo output,
  looks perfectly fine on hdmi". In both, the front-end's own layout profiles changed
  nothing, because the fault is upstream of layout - it is where the framebuffer is
  routed and in what mode, and none of that is visible anywhere in the UI. A player on
  a television gets a broken picture and no hint that video routing exists.

  So this reports, and only reports. The three settings that decide it - vga_scaler,
  direct_video, vga_mode - are deliberately absent from Best Settings (chome_ini.cpp)
  and from the editable options (chome_opt.h) because getting one wrong is a black set
  with no way back, and that judgement stands: the audience for this front-end cannot
  edit an ini from a shell. Naming what is happening costs nothing and can black out
  nothing. Where the fix is a one-word ini change the line says which word, and the
  player makes it on a machine they can still see.

  Every predicate is read from cfg and from whether an HDMI sink is attached, so the
  whole thing is a pure function of the configuration - see vp_analog_facts().
*/
#define VP_AN_31K    0x01   // an encoded analog output driven at 31 kHz: no lock on a TV
#define VP_AN_NOTUS  0x02   // the front-end is not on the analog output at all
#define VP_AN_MONO   0x04   // it is, but through the scaler, where there is no encoder
#define VP_AN_60HZ   0x08   // and at 60 Hz, whatever the set expects

#define VP_AN_LAST   VP_AN_60HZ
#define VP_AN_MAX    3      // how many can hold at once, with one to spare

/*
  The set that holds, worst first by bit order. 0 when there is nothing to say, which
  is the answer for the ordinary HDMI machine: the report only speaks when MiSTer.ini
  says the analog port is in use for something, or when no HDMI sink is attached at
  all - a default vga_mode with a display on HDMI tells us nothing about a television.

  hdmi is video_hdmi_connected(): 1 attached, 0 not, -1 unknown. Unknown counts as
  attached, the same cautious answer video.cpp gives it.
*/
int vp_analog_facts(int hdmi);

// One line for one fact, 32 characters at most - that is what the panel fits at 240p.
// 0 for anything that is not a single VP_AN_* bit.
const char *vp_analog_text(int fact);

#endif
