/*
  Classic Home - video looks.

  A short curated list of presets instead of MiSTer's filter/mask/gamma knobs.
  Each look drives two machines: the scaler, through a real MiSTer preset file
  applied with video_loadPreset() (which persists per core), and the running
  core's own display options, matched by NAME against its CONF_STR and never
  saved into its config - see the preset table in chome_video.cpp for why the
  colour work moved core-side for GB and GBA, and what stays with the scaler
  (the pixel grid, drawn by a polyphase filter so it lands on core pixel
  boundaries at any scale - the one thing a shadow mask cannot promise).

  The filter coefficients, shadow masks, gamma LUTs and .gbp palettes the
  presets reference are generated by vp_install() rather than assumed to be on
  the SD card, so the looks work on a stock install without the community
  filter packs. Files we generated are regenerated when their content changes;
  files without our marker belong to the user and are never touched.

  Every class offers one entry that turns all processing off (Sharp for the CRT
  classes, None for handhelds - None also resets the core-side effects).

  What a look does divides into colour and structure, and the division is data,
  not a special case: the palette and the colour correction are one column of the
  preset table, the pixel grid, the drop shadow and the panel's ghosting another.
  On an analog display only the colour half is applied - see vp_output_is_analog()
  below, and the table's own note about why.

  Previews are illustrations rendered in software from the same parameters, not
  captures of a running core.
*/

#ifndef CHOME_VIDEO_H
#define CHOME_VIDEO_H

#include <inttypes.h>

// Video class of a system: picks the default look.
#define VC_CONSOLE  0   // RGB-modded console on a PVM
#define VC_ARCADE   1
#define VC_COMPUTER 2   // 15 kHz home computer, i.e. plugged into a TV
#define VC_VGA      3   // 31 kHz computer monitor, no scanlines
#define VC_GB       4
#define VC_GBC      5
#define VC_GBA      6
#define VC_GG       7   // Sega Game Gear
#define VC_LYNX     8   // Atari Lynx
#define VC_WS       9   // WonderSwan, monochrome
#define VC_WSC     10   // WonderSwan Color
#define VC_NGPC    11   // Neo Geo Pocket Color
#define VC_COUNT   12

// 1 for the handheld classes: they get LCD looks and a shell, never a CRT.
int  vp_class_is_handheld(int vclass);

const char *vp_class_name(int vclass);

// Human-readable, for the "for <hardware>" heading over the shortened list.
const char *vp_class_label(int vclass);
int  vp_class_from_name(const char *s);

// Writes the filters, masks, gamma curves and preset files. Safe to call often:
// only missing files are created.
void vp_install();

int  vp_count();
const char *vp_name(int i);
const char *vp_blurb(int i);

/*
  Looks are offered per video class, not as one global list: a Game Boy game has
  no business being shown a PVM look, and a Mega Drive game has no business being
  shown an LCD one. vp_options_for() returns how many looks apply to a class and
  writes the preset indices into out[], most authentic first - so entry 0 is also
  the default. out may be null when only the count is wanted.

  On an analog display the list is shorter: a handheld look whose difference is a
  pixel grid or a scaler gamma the scaler cannot deliver is left out rather than
  offered and then found to do nothing. So the count is also the answer to "is
  there a choice worth showing here", which is what the menu bar asks it.
*/
#define VP_MAX_OPTIONS 8
int  vp_options_for(int vclass, int *out);

/*
  1 when the picture is on an analog display and only there - no HDMI sink
  attached, so whatever the routing (direct_video, vga_scaler, or the front-end's
  own takeover) a CRT or a television is what the player is looking at.

  This is what decides that a look drops its panel half: the LCD pixel grid, the
  drop shadow and the panel's ghosting simulate a screen the player is not using,
  and on a real tube they are damage. The colour half - a DMG palette, the GBA
  models' colour correction - is exactly what a Game Boy on a CRT should have and
  is applied on every output.

  It is deliberately NOT video_scaler_is_visible(), which answers the different
  question of whether the scaler output reaches a screen at all: with vga_scaler
  the scaler is in the path and pointed straight down a VGA cable at a tube.
*/
int  vp_output_is_analog();

/*
  Notice an output change under a running game and re-evaluate the look for it.
  Cheap to call every frame: it does nothing at all unless a look owns core
  options, and nothing but an i2c byte unless the answer has changed.
*/
void vp_output_poll();

// 1 when every file the preset needs exists.
int  vp_available(int i);

int  vp_default_for(int vclass);

/*
  Effective look for a system in a given class: the user's stored choice when it
  is still valid for that class, else the class default. The choice is keyed by
  system AND class, so a GBC cartridge and a DMG cartridge running in the same
  Game Boy core remember different screens.
*/
int  vp_effective(int sysidx, int vclass);
void vp_set(int sysidx, int vclass, int preset);

// Records the look to apply once the next core has booted, and applies it there.
// vclass_hint < 0 uses the system's own class.
void vp_arm_for_launch(int sysidx, int vclass_hint);
void vp_apply_pending();

/*
  Repeat the core-side half of the session's look, once the ROM is really in.
  chome_core_boot() runs before an MGL's delayed file load, and the core resets
  around that load - see the note at vp_apply_core_side(). No-op when no look
  was applied this session.
*/
void vp_reapply_core_side();

/*
  The save shield, for user_io_status_save(): suspend puts the player's own
  pre-look values back on the live status word, resume re-asserts the look.
  Wrapped around the write, a "Save settings" from any OSD persists the
  player's configuration and never the look's session values. Both no-ops when
  no look has touched anything.
*/
void vp_core_side_suspend();
void vp_core_side_resume();

// Drop the undo records and the running look. A new process does this by
// existing; only the harness, which packs many sessions into one process,
// ever needs to call it.
void vp_forget_originals();

// Applies the look the running core should have, right now rather than at next launch.
int vp_apply_now(int sysidx, int vclass_hint);

// Absolute path of a look's generated preset file, for applying it directly.
int  vp_preset_path(int i, char *out, int len);

/*
  Absolute path of a look's static preview image (classicui/lookshots/<id>.png),
  1 only when the file exists. A distribution-provided zoomed shot of the real
  effect - phosphors, grid - which the Display screen prefers over the computed
  illustration, because the real filters live in the scaler and cannot be read
  back.
*/
int  vp_lookshot_path(int i, char *out, int len);

/*
  Preview of a look, cached. When ref is non-null it is used as the source frame -
  a real capture of the user's own game - and the look is applied over it; with no
  reference a synthetic test pattern stands in.

  Either way the filter itself is a software approximation: the real filters live
  downstream in the FPGA scaler and nothing can read back from there (the capture
  buffer at MISTER_SCALER_BASEADDR holds the core's frame *before* scaling). So the
  content is real, the effect is simulated.
*/
/*
  A preview tile: the look over the player's own frame, or over a test pattern when
  there is none. `ref` is the core's frame at its NATIVE resolution (sw_native x
  sh_native) - not a magnified crop, because the look is applied at the television's
  magnification and the tile is a 1:1 crop of that. Pass 0 for the pattern.
*/
const uint32_t *vp_preview(int i, int w, int h, const uint32_t *ref, int sw_native, int sh_native);

/*
  A captured frame, put through the scaler's own arithmetic for this look, so the
  front-end can draw what the television is drawing rather than an impression of
  it. See the long note on the definition for what is exact and what is not.

  Returns 0 when the look has nothing in the scaler to apply (its whole effect is
  core-side, or it is None), in which case the caller should use the frame as it
  is. Costs a full-canvas pass of integer arithmetic: fine once when a menu opens,
  not fine every frame.
*/
/*
  Rebuild the LCD grid for the magnification the scaler is giving right now, if it
  has changed. Returns 1 when the file was rewritten. The generator only writes
  when the bytes differ, but ASKING costs a map of /dev/mem and a log line from
  upstream code, so the question is rate-limited to once a second - pass force
  when the answer is needed immediately, which is the menu opening over a game
  and about to draw the still through this very grid.
*/
int vp_grid_for_now(int force = 0);

/*
  The rectangle the scaler is putting the running game in, in panel pixels - what
  the television is actually showing, which is not the same as the frame fitted to
  the canvas. Returns 0 when there is nothing running to ask.
*/
int vp_output_rect(int *w, int *h);

/*
  How many lines the running core is really drawing, from the scaler's own header - 160
  for a GBA, 224 for most of the SNES's modes. 0 when there is nothing to ask.

  A measurement rather than a table, and it has to be: a core's line count changes with
  the game and with the region, and the one question it is used for - would this video
  mode be a whole multiple of it - is wrong the moment the number is guessed. Latched by
  vp_output_watch() before our framebuffer takes the screen, like the output rect beside
  it, because from then on the scaler describes the menu.
*/
int vp_game_height();

/*
  Keep the game's own geometry current, cheaply. Called every frame; reads the
  scaler at most once a second and never while our framebuffer owns the output,
  because from then on the scaler is describing the menu rather than the game.
*/
void vp_output_watch();

int vp_render_exact(int look, const uint32_t *src, int sw, int sh,
	uint32_t *dst, int dw, int dh);

/*
  The same, for one window of a virtual dw x dh render - which is what a preview
  tile is: the look applied at the magnification the television uses, then cropped
  1:1. Only the source rows the window reaches are touched, so a tile costs its own
  pixels rather than a full frame.
*/
int vp_render_exact_rect(int look, const uint32_t *src, int sw, int sh,
	int dw, int dh, int x0, int y0, int w, int h, uint32_t *dst);

/* ------------------------------------------------ the per-core video mode ----- */

/*
  A short list of output modes, offered per core, written into MiSTer.ini's own per-core
  section.

  A v6 beta tester asked for it: "if possible ability to change resolution per core like
  720x480i for GBA for that 3x integer scale on CRT". The want is exact and worth stating
  plainly, because it is the whole design. GBA draws 160 lines. At 720p the scaler's
  integer mode fits 4x into 720 and leaves borders; at 480p it fits 3x into 480 and fills
  the screen. Nothing here scales anything - vscale_mode=1, "use integer scale only", is
  already MiSTer's default and already the front-end's recommendation. All this does is
  hand the scaler a height that is a whole multiple of the core's.

  ## What a user could already do, and what is actually new

  Almost nothing is new, and that is deliberate. MiSTer.ini has had per-core sections
  since long before this front-end (cfg.cpp's ini_get_section), a core load restarts the
  application, and user_io_init() runs cfg_parse() and then video_init() - so `[GBA]` with
  `video_mode=2` under it already works, applied at exactly the right moment, by the
  firmware, with no help from us. What was missing was a way to do it without a text
  editor and a second machine, and a way to find out whether the display accepts the mode
  before committing to it.

  So this writes the same line a person would have typed, and the setting keeps working
  with classicui=0.

  ## Why this is safe to offer at all, when chome_opt.h refuses to

  chome_opt.h's rule 2 names `video_mode` as one of the settings that screen will not
  touch, because "a wrong value there is a black set and a card that has to come out and
  go into a PC", and that rule is right about the GLOBAL setting and stands. Three things
  make the per-core one a different question:

  1. **The menu core is never affected.** A per-core mode is scoped to one core's section,
     so the shelf always comes up at the machine's normal mode. Whatever a wrong choice
     does to one game, the player can always get back to a screen they can read and
     change it. The global setting has no such floor - that is what makes it the thing
     chome_opt.h refuses.

  2. **Nothing is written until somebody has seen it work.** Choosing a mode applies it
     live and starts a countdown; the ini is written only on a second press. A display
     that cannot lock to the mode gets fifteen seconds of black and then
     video_mode_restore() puts the configured mode back, having changed no file.

  3. **The list is short and every entry is a standard.** 60 Hz CEA and VESA modes only,
     no pixel repeat, no 50 Hz - this board's EDID is empty, so nothing can enumerate what
     the display takes, and a 50 Hz mode on a 60 Hz-only set is exactly the failure
     nothing could have predicted.

  Both defences are here rather than one, because they answer different failures: the
  short list makes a lost picture unlikely, and on a machine that cannot read an EDID
  "unlikely" is the best a list can ever be. The countdown is what makes it survivable
  when it happens anyway.

  ## Where the row is, and why not on the Display screen

  Display would be the tidy home - it already stores per system and per video class. It is
  also hidden at PROF_LO and hidden entirely when the scaler output is not what reaches
  the screen (mb_visible in chome_ui.cpp), which is to say hidden from the 240p and
  direct_video machines whose owners are the people asking for this. Options is reachable
  on every profile and every output, so the row is there.

  In a game only. A mode is chosen for the core that is running, on the display that is
  attached, by looking at the result - and none of those exist on the shelf.
*/

#define VM_MAX 8

int  vm_count();

// What goes in MiSTer.ini, and what video_mode_cmd() is handed - the same string for
// both, which is the point of widening that hook. "" for Automatic, which writes no line.
const char *vm_ini(int i);

// What the row says: "Automatic", "720x480", and so on.
const char *vm_label(int i);

// The mode's height, for the "would this be a whole multiple" line. 0 for Automatic.
int  vm_height(int i);

/*
  Which entry `[<core>]` is set to, read from MiSTer.ini rather than from cfg - cfg holds
  the value after every section that matched was applied, which cannot say whether it was
  this core's section that said it. 0 (Automatic) when the section says nothing, and also
  when it says something this list does not offer: the row then reads Automatic while the
  file still says what it said, which is the honest way round. Changing it writes ours
  over theirs; not touching it leaves theirs alone.
*/
int  vm_current(const char *core);

/*
  1 when a mode set here would change anything this machine is showing - which is whether
  the scaler's output reaches a screen at all, because that is the only thing video_mode
  shapes. See the long note on the definition for the three ways the answer is no, and for
  the version of this that was wrong.
*/
int  vm_supported();

// Which reason, so the screen can name the one that applies and the fix that goes with it.
int  vm_unsupported_is_direct();

// Applied now, nothing written. vm_restore_now() is the undo.
void vm_apply_now(int i);
void vm_restore_now();

/*
  Write it into `[<core>]`. Entry 0 removes the line rather than emptying it - an empty
  video_mode= is a parse failure that falls back to 1080p, not "no setting". Returns 1
  when the file changed, 0 when it already said this, -1 with ini_last_error() set.
*/
int  vm_write(const char *core, int i);

/* --------------------------------------------------- the analog output ----- */

/*
  What the analog output is doing to this front-end, as facts rather than as settings.

  Two users have now reported the same class of fault: a rolling picture on a CRT over
  component, and "scrambled b/w mess with rolling image on my crt with svideo output,
  looks perfectly fine on hdmi". In both, the front-end's own layout profiles changed
  nothing, because the fault is upstream of layout - it is where the framebuffer is
  routed and in what mode, and none of that is visible anywhere in the UI. A player on
  a television gets a broken picture and no hint that video routing exists.

  So this reports, and only reports. The three settings that decide it - vga_scaler,
  direct_video, vga_mode - are deliberately absent from Best Settings (chome_ini.cpp)
  and from the editable options (chome_opt.h) because getting one wrong is a black set
  with no way back, and that judgement stands: the audience for this front-end cannot
  edit an ini from a shell. Naming what is happening costs nothing and can black out
  nothing. Where the fix is a one-word ini change the line says which word, and the
  player makes it on a machine they can still see.

  Every predicate is read from cfg and from whether an HDMI sink is attached, so the
  whole thing is a pure function of the configuration - see vp_analog_facts().
*/
#define VP_AN_31K    0x01   // an encoded analog output driven at 31 kHz: no lock on a TV
#define VP_AN_NOTUS  0x02   // the front-end is not on the analog output at all
#define VP_AN_MONO   0x04   // it is, but through the scaler, where there is no encoder
#define VP_AN_60HZ   0x08   // and at 60 Hz, whatever the set expects

#define VP_AN_LAST   VP_AN_60HZ
#define VP_AN_MAX    3      // how many can hold at once, with one to spare

/*
  The set that holds, worst first by bit order. 0 when there is nothing to say, which
  is the answer for the ordinary HDMI machine: the report only speaks when MiSTer.ini
  says the analog port is in use for something, or when no HDMI sink is attached at
  all - a default vga_mode with a display on HDMI tells us nothing about a television.

  hdmi is video_hdmi_connected(): 1 attached, 0 not, -1 unknown. Unknown counts as
  attached, the same cautious answer video.cpp gives it.
*/
int vp_analog_facts(int hdmi);

// One line for one fact, 32 characters at most - that is what the panel fits at 240p.
// 0 for anything that is not a single VP_AN_* bit.
const char *vp_analog_text(int fact);

#endif
