/*
  Classic Home - video looks.

  A short curated list of presets instead of MiSTer's filter/mask/gamma knobs.
  Each one is written out as a real MiSTer preset file and applied with
  video_loadPreset(), which persists per core, so nothing here is a parallel
  implementation of the scaler - it drives the existing one.

  The filter coefficients, shadow masks and gamma LUTs the presets reference are
  generated by vp_install() rather than assumed to be on the SD card, so the
  looks work on a stock install without the community filter packs. Existing
  files are never overwritten.

  Previews are illustrations rendered in software from the same parameters, not
  captures of a running core.
*/

#ifndef CHOME_VIDEO_H
#define CHOME_VIDEO_H

#include <inttypes.h>

// Video class of a system: picks the default look.
#define VC_CONSOLE  0   // RGB-modded console on a PVM
#define VC_ARCADE   1
#define VC_COMPUTER 2   // 15 kHz home computer, i.e. plugged into a TV
#define VC_VGA      3   // 31 kHz computer monitor, no scanlines
#define VC_GB       4
#define VC_GBC      5
#define VC_GBA      6
#define VC_GG       7   // Sega Game Gear
#define VC_LYNX     8   // Atari Lynx
#define VC_WS       9   // WonderSwan, monochrome
#define VC_WSC     10   // WonderSwan Color
#define VC_NGPC    11   // Neo Geo Pocket Color
#define VC_COUNT   12

// 1 for the handheld classes: they get LCD looks and a shell, never a CRT.
int  vp_class_is_handheld(int vclass);

const char *vp_class_name(int vclass);

// Human-readable, for the "for <hardware>" heading over the shortened list.
const char *vp_class_label(int vclass);
int  vp_class_from_name(const char *s);

// Writes the filters, masks, gamma curves and preset files. Safe to call often:
// only missing files are created.
void vp_install();

int  vp_count();
const char *vp_name(int i);
const char *vp_blurb(int i);

/*
  Looks are offered per video class, not as one global list: a Game Boy game has
  no business being shown a PVM look, and a Mega Drive game has no business being
  shown an LCD one. vp_options_for() returns how many looks apply to a class and
  writes the preset indices into out[], most authentic first - so entry 0 is also
  the default.
*/
#define VP_MAX_OPTIONS 8
int  vp_options_for(int vclass, int *out);

// 1 when every file the preset needs exists.
int  vp_available(int i);

int  vp_default_for(int vclass);

/*
  Effective look for a system in a given class: the user's stored choice when it
  is still valid for that class, else the class default. The choice is keyed by
  system AND class, so a GBC cartridge and a DMG cartridge running in the same
  Game Boy core remember different screens.
*/
int  vp_effective(int sysidx, int vclass);
void vp_set(int sysidx, int vclass, int preset);

// Records the look to apply once the next core has booted, and applies it there.
// vclass_hint < 0 uses the system's own class.
void vp_arm_for_launch(int sysidx, int vclass_hint);
void vp_apply_pending();

/*
  Preview of a look, cached. When ref is non-null it is used as the source frame -
  a real capture of the user's own game - and the look is applied over it; with no
  reference a synthetic test pattern stands in.

  Either way the filter itself is a software approximation: the real filters live
  downstream in the FPGA scaler and nothing can read back from there (the capture
  buffer at MISTER_SCALER_BASEADDR holds the core's frame *before* scaling). So the
  content is real, the effect is simulated.
*/
const uint32_t *vp_preview(int i, int w, int h, const uint32_t *ref);

#endif
