import math, sys
PHASES=64; GRID_GUTTER=0.22; GRID_DEPTH=0.42
SHADOW_WIDTH=0.30; SHADOW_MIX=0.35; SHADOW_DIM=0.10
GEN_MARK="generated by Classic Home"
BUILD="f77af4f8"   # gen_commit stamps this; copied so the front-end sees its own file

def filter_line(w,gain):
    c=[]
    for t in range(4):
        v=int(round(w[t]*gain*128.0))
        # C lround: half away from zero
        exact=w[t]*gain*128.0
        v=int(math.floor(exact+0.5)) if exact>=0 else -int(math.floor(-exact+0.5))
        c.append(max(-255,min(255,v)))
    return "%4d,%4d,%4d,%4d\n"%tuple(c)

def build(scale, shadow, mode="orig", mix=SHADOW_MIX, dim=SHADOW_DIM, bscale=1.0):
    centre=0.5; half=GRID_GUTTER/2; duty=GRID_GUTTER
    step=1.0/scale if scale>=2 else None
    if scale>=2:
        best=0.0; bestd=2.0
        for x in range(scale):
            u=(x+0.5)/scale-0.5
            frac=u-math.floor(u)
            d=abs(frac-0.5)
            if d<bestd: bestd=d; best=frac
        centre=best; half=(step*0.8)/2; duty=step
    out="# %s\n"%GEN_MARK
    out+="# LCD grid for %dx: one dark pixel per source pixel at %.0f%% depth%s\n\n"%(
        scale if scale else 0, GRID_DEPTH*100, ", with the pixel shadow" if shadow else "")
    soft=1.0/PHASES
    boost=1.0/(1.0-GRID_DEPTH*duty)
    if boost>1.30: boost=1.30
    boost*=bscale
    scentre=(centre+step)%1.0 if (step and mode=="snap") else None
    for p in range(PHASES):
        x=p/PHASES
        d=abs(x-centre)
        if d>0.5: d=1.0-d
        e=0.0
        if d<half: e=1.0
        elif d<half+soft: e=1.0-(d-half)/soft
        w=[0.0,0.0,0.0,0.0]
        cur = 1 if x<0.5 else 2
        w[cur]=1.0
        gain=boost*(1.0-GRID_DEPTH*e)
        if shadow:
            if mode=="orig":
                if x>0.5:
                    into=(x-0.5)/0.5
                    if into<SHADOW_WIDTH:
                        f=1.0-into/SHADOW_WIDTH
                        w[1]+=mix*f*w[2]; w[2]-=mix*f*w[2]
                        gain*=1.0-dim*f
            else:  # snap: one sampled phase after the gutter, same width as the gutter
                sd=abs(x-scentre)
                if sd>0.5: sd=1.0-sd
                s=0.0
                if sd<half: s=1.0
                elif sd<half+soft: s=1.0-(sd-half)/soft
                if s>0:
                    prev=cur-1
                    w[prev]+=mix*s*w[cur]; w[cur]-=mix*s*w[cur]
                    gain*=1.0-dim*s
        out+=filter_line(w,gain)
    out+="# build %s\n"%BUILD
    return out

if __name__=="__main__":
    ref=open('fx/filters/ClassicHome LCD Grid.txt').read()
    mine=build(3,False)
    print("plain grid port matches the card:", mine==ref)
    ref2=open('fx/filters/ClassicHome LCD Grid Shadow.txt').read()
    mine2=build(3,True)
    print("shadow grid port matches the card:", mine2==ref2)
    if mine!=ref:
        a=ref.split('\n'); b=mine.split('\n')
        for i,(x,y) in enumerate(zip(a,b)):
            if x!=y: print("  first diff line %d: card=%r mine=%r"%(i+1,x,y)); break
